[workspace]
resolver = "2"
rust-version = "1.62.1"  # also set in CI
members = [
    "graphql_client",
    "graphql_client_cli",
    "graphql_client_codegen",
    "graphql-introspection-query",
    "graphql_query_derive",

    # Example crates.
    "examples/*",
]
